#!/bin/bash

# alias for dotfiles handling, also making sure that zsh completion works
alias dot='git --git-dir=$HOME/.dots.git/ --work-tree=$HOME' # dotfile handling
compdef dot='git'
setopt complete_aliases

alias shutdown="systemctl poweroff"
# shellcheck disable=SC2139
alias {vi,vim}="nvim"
alias todo="nvim ~/Documents/irl/todo.txt"
alias poly="nohup sh ~/.config/polybar/launch.sh > /dev/null 2>&1 &"
alias poly_reload="pkill -USR1 polybar"
alias gsync="grive -p ~/GoogleDrive"
alias imgur="sh ~/Scripts/imgur.sh"
alias mutt="sh ~/Scripts/mutt.sh"
alias evince="evince 2>/dev/null"
# replace antibody with next gen version of it
alias antibody="antidote"
# https://github.com/ranger/ranger/issues/2608
alias ranger="ranger"

# .Xresources handling - reload, merge
alias xm="xrdb -merge ~/.Xresources"
alias xr="xrdb ~/.Xresources"

#Basically an ls replacement for tree
alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

#A tree function for files as well
alias ftree="find | sed 's|[^/]*/|- |g'"

# Detect which `ls` flavor is in use
if ls --human-readable >/dev/null 2>&1; then # GNU `ls`
    colorflag='--color'
    alias ls='ls ${colorflag} --human-readable --group-directories-first --classify'
else # OS X `ls`
    colorflag='-G'
    alias ls='ls ${colorflag}'
fi

# Basic colored ls
# List all files colorized in long format
# shellcheck disable=SC2139
alias l="ls -lF ${colorflag}"
# List all files colorized in long format, including dot files
# shellcheck disable=SC2139
alias la="ls -laF ${colorflag}"
# List only directories
# shellcheck disable=SC2139
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'"

# Ask when deleting multiple
alias rm="rm -I"

# All pagers except less bound to vless
# shellcheck disable=SC2139
alias {vl,more,most,view}="vless"

# Config editing binds
alias cfv="vim ~/.config/nvim/init.lua --cmd 'cd ~/.config/nvim'"
alias cfi="vim ~/.config/i3/config"
alias cfr="vim ~/.config/ranger/rc.conf"
alias cfm="vim ~/.config/mutt/muttrc"
alias cfp="vim ~/.config/polybar/config"
alias cfd="vim ~/.config/dunst/dunstrc"
alias cfx="vim ~/.Xresources"
alias cfz="vim ~/.config/zsh/.zshrc"
alias cft="vim ~/.tmux.conf"
alias cfa="vim ~/.config/zsh/aliasrc"
alias cfc="vim ~/.config/alacritty/alacritty.yml"
alias cfy="vim ~/.yabairc"
alias cfs="vim ~/.skhdrc"

# Used for toggling colors for playing csgo
alias csgo="sh ~/Scripts/vibrance.sh"

# Use i3lock when afk
alias afk="sh ~/Scripts/lock.sh"

# Reload shell
alias reload='exec $SHELL -l'

# Used for grepping cars from the zipped
# Danish motorregister
alias cargrep="zgrep -B 10 -A 60 -m 1 -n"

# Get week number
alias week='date +%V'

# Sped up cd navigation
alias cd.="cd .."
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Remove all local branches that 'gone' on the remote. Lanuguage dependent
# https://stackoverflow.com/questions/7726949/remove-local-branches-no-longer-on-remote/38404202#38404202
# shellcheck disable=SC2139
alias gprune="git fetch -p && git branch --merged | egrep -v '(^\*|master|dev|develop|development)' | xargs git branch -d"

# Shortcut for running work script
alias work="sh ~/Scripts/linux/work.sh"

# Start an instance of firefox with no profile
alias fx='firefox --new-instance --profile $(mktemp -d)'

# Detect the Operating System
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS: Open KeyCastr
    alias sk="open -a KeyCastr"
else
    # Linux: Run screenkey with defaults
    alias sk="screenkey -p fixed -g 20%x10%+40%-10%"
fi

# Simpler access to lazydocker
alias lzd="lazydocker"

# Aliases for cleaning up $HOME
alias weechat='weechat -d "$HOME/.config/weechat"'
alias wget='wget --hsts-file="$HOME/.cache/wget-hsts"'
