# Shell variables
# Generated by 'wal'
wallpaper='1473438101572.jpg'

# Special
background='#040811'
foreground='#FDFCF8'
cursor='#FDFCF8'

# Colors
color0='#040811'
color1='#BE7090'
color2='#839582'
color3='#A29BA3'
color4='#D8B8B2'
color5='#F0E4D5'
color6='#FBF7EA'
color7='#FDFCF8'
color8='#666666'
color9='#BE7090'
color10='#839582'
color11='#A29BA3'
color12='#D8B8B2'
color13='#F0E4D5'
color14='#FBF7EA'
color15='#FDFCF8'
