# ALIASES
alias ls="ls-i --color=auto"
alias dir="dir-i --color=auto"
alias vdir="vdir-i --color=auto"
alias pacyyu="sudo pacman -Syyu"
alias ls="ls --color"
alias shutdown="systemctl poweroff"
alias pacyy="sudo pacman -Syy"
alias pacyu="sudo pacman -Syu"
alias vim="vim"
alias pdf="zathura"
alias poly="sh ~/.config/polybar/launch.sh"
alias rm="rm -I"
alias gsync="grive -p ~/GoogleDrive"
#Basically an ls replacement for tree
alias tree="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"
alias ftree="find | sed 's|[^/]*/|- |g'"

# Config editing binds
alias cfv="vim ~/.vimrc"
alias cfi="vim ~/.config/i3/config"
alias cfr="vim ~/.config/ranger/rc.conf"
alias cfm="vim ~/.muttrc"
alias cfp="vim ~/.config/polybar/config"
alias cfd="vim ~/.config/dunst/dunstrc"
